[[plugins]]
repo = 'Shougo/neocomplete'
if = 'has("lua")'
on_i = 1

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
on_i = 1

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
on_i = 1

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
on_i = 1

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']
on_i = 1

